version: '3.9'

services:
    app:
        build: .
        container_name: dcc-app
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: dccdocumentmanagementsystem
            DB_USERNAME: root
            DB_PASSWORD: secret

    queue:
        build: .
        container_name: dcc-queue
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: dccdocumentmanagementsystem
            DB_USERNAME: root
            DB_PASSWORD: secret
        command: php artisan queue:work --sleep=3 --tries=3

    db:
        image: mysql:8.0
        container_name: dcc-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: dccdocumentmanagementsystem
        volumes:
            - dbdata:/var/lib/mysql
            - ./database/backup:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

volumes:
    dbdata:
